<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function fortune_teller_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id === 'node_blog_form' || $form_id === 'node_blog_edit_form') {
    $form['actions']['submit']['#submit'][] = 'fortune_teller_add_fortune_submit';
  }
}

/**
 * Custom submit handler to add fortune.
 */
function fortune_teller_add_fortune_submit(array &$form, FormStateInterface $form_state) {
  $node = $form_state->getFormObject()->getEntity();
  if ($node instanceof \Drupal\node\NodeInterface && $node->bundle() == 'blog') {
    \Drupal::service('fortune_teller.fortune_service')->addFortune($node);
  }
}